# Generated by Django 3.1.6 on 2021-03-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_feature', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
