# Generated by Django 3.1.6 on 2021-04-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_feature', '0003_auto_20210419_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': (('universal', 'Univeral Chat'),)},
        ),
    ]
