# Generated by Django 3.1.6 on 2021-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_feature', '0004_auto_20210419_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='universal_chat',
            field=models.BooleanField(default=False),
        ),
    ]
